# SimpleVein – Standardkonfiguration (immer an; Sneak = AUS)
enabled-by-default: true         # Spieler haben VeinMining an, bis sie /vein toggle machen
disable-when-sneaking: true      # Sneak -> VeinMining AUS (invertierte Steuerung)
max-blocks: 64                   # Sicherheitslimit pro Abbau
diagonals: false                 # nur 6-Nachbarn (keine Diagonalen)

allowed-tools:                   # nur mit diesen Werkzeugen (optional)
  - WOODEN_PICKAXE
  - STONE_PICKAXE
  - IRON_PICKAXE
  - GOLDEN_PICKAXE
  - DIAMOND_PICKAXE
  - NETHERITE_PICKAXE
# Tipp: Wenn du ALLE Tools erlauben möchtest, leere die Liste komplett.

whitelist:                       # nur diese Blöcke werden vein-mined
  - COAL_ORE
  - IRON_ORE
  - COPPER_ORE
  - GOLD_ORE
  - LAPIS_ORE
  - REDSTONE_ORE
  - DIAMOND_ORE
  - EMERALD_ORE
  - NETHER_QUARTZ_ORE
  - NETHER_GOLD_ORE
  - ANCIENT_DEBRIS
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_COPPER_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_EMERALD_ORE

