name: SimpleVein
main: dev.yourserver.simplevein.SimpleVeinPlugin
version: 1.0.1
api-version: '1.20'
author: yourserver
commands:
  vein:
    description: Toggle/konfigurieren
    usage: /vein [toggle|on|off|reload]
    permission: simplevein.use
permissions:
  simplevein.use:
    default: true
  simplevein.reload:
    default: op
  simplevein.bypass-limit:
    default: op


